### ISSUE TITLE
How to plot the loss terrain along with the path taken by the optimizer

### ISSUE THREAD

**Issue by chaituValKanO** [michaelrzhang/lookahead#1]
Hello,

Can you help me understand how did you plot the loss terrain in 2D along with the path taken by the optimizer? There are millions of parameters involved and I want to understand how to bring them to 2D

**Comment by michaelrzhang** [comment]
Great question; we project every point in weight space (dimension **n**, which can be millions as you said) into a plane defined by two orthogonal vectors, both of dimension **n**.

We choose these vectors by looking at the first, middle, and final weights of the inner optimization algorithm. 
Vector 1 = middle weight - first weight
Vector 2 = last weight - first weight - (amount explained by Vector 1)
where the amount explained by Vector 1 is analogous to what is done in the [Gram-Schmidt process](https://en.wikipedia.org/wiki/Gram%E2%80%93Schmidt_process)

**Comment by michaelrzhang** [comment]
Closing, feel free to re-open if still unclear.
