### ISSUE TITLE
Lookahead Questions :)

### ISSUE THREAD

**Issue by danielhanchen** [michaelrzhang/lookahead#4]
By the way fantastic work Michael on Lookahead!
I also watched 2 tutorials / workshops you did on Youtube! Great explanation!

I was wondering, if you were doing future research into how to make Lookahead better? Many loss landscapes show that neural networks are weirdly parabolic, just there might be many many parabolas in the loss landscape. Likewise, there are weird long valleys etc.

Not sure why but Lookahead reminds me of like conjugate gradient (not exactly), but ie the perpendicular to the gradient is the closest to the optimum.

On another note, I was just thinking of like trying to "incorporate" somehow all the fast weight updates into some sort of average direction (ie like a conjugate direction).

I haven't tried it myself, but essentially, you take the "average" of all the slow weights to the new location of the fast weight.
![image](https://user-images.githubusercontent.com/23090290/95343791-a6ecfb80-0904-11eb-832e-c4009b96af33.png)

I'm just spouting random ideas. I'll probs test them.
![image](https://user-images.githubusercontent.com/23090290/95345489-7efe9780-0906-11eb-9548-9b72a4e82a84.png)

It's entirely possible using stochastic gradients and "averaging them" then adding it to the Lookahead slow weight might overshoot or something.

Anyways once again good work on Lookahead Michael! [I'm using it in conjuction with RAdamW [ie Ranger]]

**Comment by danielhanchen** [comment]
Disregard the ideas.
Tested them, it's absolutely worse than normal Lookahead.
![image](https://user-images.githubusercontent.com/23090290/95419302-16a2cb00-0985-11eb-8c41-2cf1069eb595.png)

Oh well.

**Comment by michaelrzhang** [comment]
Thank you for the comments! It's great that you're trying out different tweaks to the algorithm. I have found it interesting that choosing a fixed alpha does very well, and investigating in detail why that is the case could be a nice direction.
